# Unidad 2 Actividad 1

**1. Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida de matriz en la que cada elemento es una suma de elementos de las 2 matrices? (solo puede usar numpy como librería, si realiza la matriz con otro paquete el ejercicio no es válido)**

In [2]:
import numpy as np

In [4]:
dimension = 3
matriz_1 = np.random.randint(0,10,size=(dimension,dimension))
matriz_2 = np.random.randint(0,10,size=(dimension,dimension))

In [9]:
print(matriz_1,"\n\n", matriz_2)

[[6 6 1]
 [1 5 8]
 [2 1 7]] 

 [[9 8 4]
 [7 2 1]
 [0 3 0]]


In [16]:
matriz_3 = np.add(matriz_1,matriz_2)
matriz_3

array([[15, 14,  5],
       [ 8,  7,  9],
       [ 2,  4,  7]])

**2. Cree una matriz de identidad de dimensión 4.**

In [17]:
matriz_identidad = np.identity(dimension)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**3.Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una
matriz numpy booleana.**

In [18]:
matriz_booleana = matriz_identidad == 1
matriz_booleana

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

**4. Genere una secuencia de números en forma de matriz numpy de 0 a
100 con espacios de 2 números, por ejemplo: 0, 2, 4 ...**

In [23]:
matriz_5 = [i for i in range(100) if i%2 == 0]
matriz_5

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

- ¿Qué es la librería numpy?

    **R:    **
    
- ¿Conocemos los términos de vectores y matrices?

    **R:**