## Welcome to RandomCracy

In [3]:
data_science_students = [
    "Claudio Bahamonde",
    "Felipe Abarzúa",
    "Diego Rodriguez",
    "Javier Pizarro",
    "Smilling Battaglini",
    "Pamela Labbé",
    "Marilina Fuentes",
    "Jaime Castillo",
    "Rodrigo Castillo",
    "Ignacia Arenas",
    "Luis reyes",
    "Felipe Cabello",
    "Polette Pino",
    "Karen Lobos",
    "Diego Ávila",
    "Constanza Guzman",
    "Nicole Alejandra Araya",
    "Carlos Andrés Abarca",
    "Marco Antonio Ramos",
    "Claudia Araya",
    "Daniela Hernández",
    "Sergio Ananias",
    "Alexis Bacian",
    "Cristian Alvarez",
    "Nubia Ascencio",
    "Veronica Marín",
    "Liliana Romina Garmendia",
    "Rocio Macari",
    "Loreto Llambias",
    "Braulio Valdés",
]

In [4]:
import random

def random_student():
    return random.choice(data_science_students)

In [5]:
random_student()

'Karen Lobos'

## Selección condicional en un array

In [17]:
import numpy as np
# fijar la semilla para que los resultados sean reproducibles
np.random.seed(0)

In [8]:
# crear un array de 20 elmentos con valores enteros aleatorios entre 0 y 10

arreglo = np.random.randint(0, 10, 20)
arreglo

array([9, 2, 6, 0, 4, 3, 1, 2, 4, 9, 8, 9, 4, 8, 9, 8, 4, 6, 7, 1])

In [15]:
# filtrar los elementos del array que sean mayores a 8

mascara_numeros_grandes = arreglo >= 0
mascara_numeros_grandes

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [16]:
datos_filtrados = arreglo[mascara_numeros_grandes]
datos_filtrados

array([9, 2, 6, 0, 4, 3, 1, 2, 4, 9, 8, 9, 4, 8, 9, 8, 4, 6, 7, 1])

In [19]:
# filtrar los elementos pares del array
print(arreglo)
mascara_numeros_pares = arreglo % 2 == 0
mascara_numeros_pares

[9 2 6 0 4 3 1 2 4 9 8 9 4 8 9 8 4 6 7 1]


array([False,  True,  True,  True,  True, False, False,  True,  True,
       False,  True, False,  True,  True, False,  True,  True,  True,
       False, False])

In [20]:
datos_pares = arreglo[mascara_numeros_pares]
datos_pares

array([2, 6, 0, 4, 2, 4, 8, 4, 8, 8, 4, 6])

In [22]:
# suma de dos arrays de la misma dimensión
arreglo_1 = np.random.randint(0, 10, 5)
print(arreglo_1)

arreglo_2 = np.random.randint(0, 10, 5)
print(arreglo_2)

[7 6 8 8 1]
[6 7 7 8 1]


In [27]:
np.exp(arreglo_1)

array([1.09663316e+03, 4.03428793e+02, 2.98095799e+03, 2.98095799e+03,
       2.71828183e+00])

In [28]:
arreglo_1.dot(arreglo_2)

205

In [29]:
np.sum(arreglo_1 * arreglo_2)

205

In [30]:
random_student()

'Liliana Romina Garmendia'

## Pandas

In [32]:
random_student()

'Alexis Bacian'

In [1]:
import pandas as pd

In [2]:
# crear un dataframe de estudiantes de matematica a partir de un diccionario

estudiantes_ds = {
    "nombre": [
        "Claudio Bahamonde",
        "Felipe Abarzúa",
        "Diego Rodriguez",
        "Javier Pizarro",
        "Smilling Battaglini",
        "Pamela Labbé",
        "Marilina Fuentes",
    ],
    "edad": [25, 26, 27, 28, 29, 30, 31],
    "nota": [1, 2, 3, 4, 5, 6, 7],
}

estudiantes_ds_df = pd.DataFrame(estudiantes_ds)

In [3]:
estudiantes_ds_df

nombre  edad  nota
0    Claudio Bahamonde    25     1
1       Felipe Abarzúa    26     2
2      Diego Rodriguez    27     3
3       Javier Pizarro    28     4
4  Smilling Battaglini    29     5
5         Pamela Labbé    30     6
6     Marilina Fuentes    31     7

In [4]:
estudiantes_ds_df.dtypes

nombre    object
edad       int64
nota       int64
dtype: object

In [5]:
estudiantes_ds_df.describe()

edad      nota
count   7.000000  7.000000
mean   28.000000  4.000000
std     2.160247  2.160247
min    25.000000  1.000000
25%    26.500000  2.500000
50%    28.000000  4.000000
75%    29.500000  5.500000
max    31.000000  7.000000

In [6]:
## Analisis de datos desde un archivo csv

In [9]:
directorio_datos = "/home/edgar/Downloads/ds-awesome-students"
nombre_archivo = "titanic.csv"
print(f"{directorio_datos}/{nombre_archivo}")

import csv
# cargar data desde un archivo csv donde cada fila esta entre comillas
titanic_df = pd.read_csv(
    f"{directorio_datos}/{nombre_archivo}",
    sep=",",
    quotechar='"',
    quoting=csv.QUOTE_ALL,
)

/home/edgar/Downloads/ds-awesome-students/titanic.csv


EmptyDataError: No columns to parse from file

In [70]:
# leer lineas del archivo csv y eliminar las ""
with open(f"{directorio_datos}/{nombre_archivo}", "r") as archivo:
   
    lines = archivo.readlines()

    for line in lines:
        line = line.replace('"', "")
        print(line)

        break

In [65]:
c = '"ho"la"'
print(c.replace('"', ''))

hola
