In [3]:
import numpy as np

In [7]:
arreglo = np.random.randint(0,10,20)

In [10]:
mascara_numeros_grandes = arreglo > 0
mascara_numeros_grandes

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False])

In [12]:
mascara_numeros_pares = arreglo % 2 == 0
mascara_numeros_pares

array([False, False,  True,  True, False,  True, False,  True,  True,
       False, False,  True, False, False,  True,  True,  True, False,
        True,  True])

In [13]:
datos_pares = arreglo[mascara_numeros_pares]
datos_pares

array([8, 4, 2, 2, 8, 6, 2, 8, 0, 2, 0])

# Pandas

In [2]:
import pandas as pd

In [20]:
diccionario = {
    "estudiantes":["Rodrigo", "Nicolas", "Abraham"],
    "edad":[20,21,22],
    "nota":[2.2,3.3,4.4]
}

In [21]:
df = pd.DataFrame(diccionario)
df

estudiantes  edad  nota
0     Rodrigo    20   2.2
1     Nicolas    21   3.3
2     Abraham    22   4.4

In [3]:
datos = pd.read_csv('gender_submission.csv')

In [4]:
datos

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]